
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "tutorials/DataCollectionSAC.py"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

        Click :ref:`here <sphx_glr_download_tutorials_DataCollectionSAC.py>`
        to download the full example code

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_tutorials_DataCollectionSAC.py:


SAC Database
============

In this Tutorial we are going to get all good receiver functions for the year
2018 for station IU-HRV ([Adam Dziewonski
Observatory](http://www.seismology.harvard.edu/hrv.html)).

To Compute the receiver function we need to download and organize the observed
data. PyGLImER will automatically take care of these things for you in the
background, but do check out the 'Database Docs' if you aren't familiar.

Downloading Event & Station Metadata
------------------------------------

To download the data we use the :class:`pyglimer.waveform.request.Request`
class. The first method from this class that we are going to use is the
download event catalog public method
:func:`pyglimer.waveform.request.Request.download_evtcat`, to get a set
of events that contains all wanted earthquakes. This method is launched
automatically upon initialization.

To initialize said `class` we setup a parameter dictionary, with all the needed
information. Let's look at the expected information:

.. GENERATED FROM PYTHON SOURCE LINES 28-31

.. code-block:: default

    # sphinx_gallery_thumbnail_number = 1
    # sphinx_gallery_dummy_images = 1








.. GENERATED FROM PYTHON SOURCE LINES 32-33

First let's get a path where to create the data.

.. GENERATED FROM PYTHON SOURCE LINES 33-80

.. code-block:: default



    # Some needed Imports
    import os
    from obspy import UTCDateTime
    from pyglimer.waveform.request import Request

    # Get notebook path for future reference of the database:
    try: db_base_path = ipynb_path
    except NameError:
        try: db_base_path = os.path.dirname(os.path.realpath(__file__))
        except NameError: db_base_path = os.getcwd()


    # Define file locations
    proj_dir = os.path.join(db_base_path, 'tmp', 'database_sac')



    request_dict = {
        # Necessary arguments
        'proj_dir': proj_dir,
        'raw_subdir': os.path.join('waveforms', 'raw'),# Directory of the waveforms
        'prepro_subdir': os.path.join('waveforms', 'preprocessed'),  # Directory of the preprocessed waveforms
        'rf_subdir': os.path.join('waveforms', 'RF'),  # Directory of the receiver functions
        'statloc_subdir': 'stations', # Directory stations
        'evt_subdir': 'events',       # Directory of the events
        'log_subdir': 'log',          # Directory for the logs
        'loglvl': 'WARNING',          # logging level
        'format': 'sac',              # Format to save database in
        "phase": "P",                 # 'P' or 'S' receiver functions
        "rot": "RTZ",                 # Coordinate system to rotate to
        "deconmeth": "waterlevel",    # Deconvolution method
        "starttime": UTCDateTime(2021, 1, 1, 0, 0, 0), # Starttime of database.
                                                    # Here, starttime of HRV
        "endtime": UTCDateTime(2021, 7, 1, 0, 0, 0), # Endtimetime of database
        # kwargs below
        "pol": 'v',                   # Source wavelet polaristion. Def. "v" --> SV
        "minmag": 5.5,                # Earthquake minimum magnitude. Def. 5.5
        "event_coords": None,         # Specific event?. Def. None
        "network": "IU",              # Restricts networks. Def. None
        "station": "HRV",             # Restricts stations. Def. None
        "waveform_client": ["IRIS"],  # FDSN server client (s. obspy). Def. None
        "evtcat": None,               # If you have already downloaded a set of
                                      # events previously, you can use them here
    }








.. GENERATED FROM PYTHON SOURCE LINES 81-83

Now that all parameters are in place, let's initialize the 
:class:`pyglimer.waveform.request.Request`

.. GENERATED FROM PYTHON SOURCE LINES 83-87

.. code-block:: default


    # Initializing the Request class and downloading the data
    R = Request(**request_dict)








.. GENERATED FROM PYTHON SOURCE LINES 88-90

The initialization will look for all events for which data is available. To see 
whether the events make sense we plot a map of the events:

.. GENERATED FROM PYTHON SOURCE LINES 90-101

.. code-block:: default


    import matplotlib.pyplot as plt
    from pyglimer.plot.plot_utils import plot_catalog
    from pyglimer.plot.plot_utils import set_mpl_params

    # Setting plotting parameters
    set_mpl_params()

    # Plotting the catalog
    plot_catalog(R.evtcat)




.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_001.png
   :alt: DataCollectionSAC
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_001.png
   :class: sphx-glr-single-img





.. GENERATED FROM PYTHON SOURCE LINES 102-103

We can also quickly check how many events we gathered.

.. GENERATED FROM PYTHON SOURCE LINES 103-106

.. code-block:: default


    print(f"There are {len(R.evtcat)} available events")





.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    There are 289 available events




.. GENERATED FROM PYTHON SOURCE LINES 107-128

Downloading waveform data and station information
-------------------------------------------------

The next step on our journey to receiver functions is retrieving
the corresponding waveform data.
To retrieve the waveform data, we can two different public methods
of `Request`: `download_waveforms()` or, as in this case `download_waveforms_small_db()`.

Both methods use the station and event locations to get viable
records of receiver function depending on epicentral distance and
traveltimes.

`download_waveforms()` relies on obspy's massdownloader and is best suited for
extremely large databases (i.e., from many different networks and stations).
`download_waveforms_small_db()` is faster for downloads from few stations and, additionally,
has the advantage that the desired networks and stations can be defined as lists and not only
as strings. Note that this method requires you to define the channels, you'd like to download
(as a string, wildcards allowed).

***NOTE:*** This might take a while.


.. GENERATED FROM PYTHON SOURCE LINES 128-131

.. code-block:: default


    R.download_waveforms_small_db(channel='BH?')





.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    --> Enter TOA event loop for station IU.HRV




.. GENERATED FROM PYTHON SOURCE LINES 132-133

Let's have a quick look at how many miniseeds we actually downloaded.

.. GENERATED FROM PYTHON SOURCE LINES 133-143

.. code-block:: default


    from glob import glob

    # Path to the where the miniseeds are stored
    data_storage = os.path.join(
        proj_dir, 'waveforms','raw','P','**', '*.mseed')

    # Print output
    print(f"Number of downloaded waveforms: {len(glob(data_storage))}")





.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    Number of downloaded waveforms: 69




.. GENERATED FROM PYTHON SOURCE LINES 144-171

The final step to get you receiver function data is the preprocessing. 
Although it is hidden in a single function, which
is :func:`pyglimer.waveform.request.Request.preprocess`
A lot of decisions are being made:

Processing steps:
1. Clips waveform to the right length (tz before and ta after theorethical 
arrival.)
2. Demean & Detrend
3. Tapering
4. Remove Instrument response, convert to velocity &
simulate havard station
5. Rotation to NEZ and, subsequently, to RTZ.
6. Compute SNR for highpass filtered waveforms (highpass f defined in 
qc.lowco) If SNR lower than in qc.SNR_criteria for all filters, rejects 
waveform.
7. Write finished and filtered waveforms to folder
specified in qc.outputloc.
8. Write info file with shelf containing station,
event and waveform information.
9. (Optional) If we had chosen a different coordinate system in ``rot``
than RTZ, it would now cast the preprocessed waveforms information
that very coordinate system.
10. Deconvolution with method ``deconmeth`` from our dict is perfomed.

It again uses the request class to perform this. The ``if __name__ ...``
expression is needed for running this examples

.. GENERATED FROM PYTHON SOURCE LINES 171-174

.. code-block:: default


    R.preprocess(hc_filt=1.5, client='single')





.. rst-class:: sphx-glr-script-out

 .. code-block:: none

      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 37.79it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:07,780 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.76549496 0.97226612 6.74721243]\n [0.76747878 0.99470118 6.35524615]\n [1.89990656 1.24512503 6.25358232]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.76549496 0.97226612 6.74721243]\n [0.76747878 0.99470118 6.35524615]\n [1.89990656 1.24512503 6.25358232]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 25.44it/s]    100%|##########| 3/3 [00:00<00:00, 25.39it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4716.23it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5487.53it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5801.25it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 45.97it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:07,903 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.57032401 1.51985421 4.18286722]\n [0.54352496 1.4341365  3.79920419]\n [1.08498482 0.7031882  1.88781185]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.57032401 1.51985421 4.18286722]\n [0.54352496 1.4341365  3.79920419]\n [1.08498482 0.7031882  1.88781185]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.16it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:07,956 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.33773937 1.86126275 0.17455782]\n [0.53010265 1.29019989 0.47216992]\n [0.9723987  1.79061754 2.24415297]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.33773937 1.86126275 0.17455782]\n [0.53010265 1.29019989 0.47216992]\n [0.9723987  1.79061754 2.24415297]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:08,008 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.1327371  0.84565732 6.6403446 ]\n [1.66057428 0.77881922 5.00261798]\n [1.83955158 0.69673167 4.28499293]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.1327371  0.84565732 6.6403446 ]\n [1.66057428 0.77881922 5.00261798]\n [1.83955158 0.69673167 4.28499293]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 28.85it/s]    100%|##########| 3/3 [00:00<00:00, 28.80it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,063 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.02230188 0.27012247 0.70190507]\n [1.93474814 0.28076508 0.55774396]\n [5.12271503 0.42159929 2.22174124]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.02230188 0.27012247 0.70190507]\n [1.93474814 0.28076508 0.55774396]\n [5.12271503 0.42159929 2.22174124]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:08,118 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.78628633 0.95708908 1.94408249]\n [0.79765119 0.85845994 1.89457661]\n [3.76322185 0.40506828 7.62107585]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.78628633 0.95708908 1.94408249]\n [0.79765119 0.85845994 1.89457661]\n [3.76322185 0.40506828 7.62107585]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 27.39it/s]    100%|##########| 3/3 [00:00<00:00, 27.34it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,173 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.24788576 0.69241528 0.65345473]\n [1.25875122 0.70820261 0.66218288]\n [1.54017682 0.8834641  1.25950846]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.24788576 0.69241528 0.65345473]\n [1.25875122 0.70820261 0.66218288]\n [1.54017682 0.8834641  1.25950846]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.38it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,229 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.57508417 1.31958902 2.52393377]\n [2.86235725 1.44927499 2.88420866]\n [1.41702297 2.20668449 2.3486472 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.57508417 1.31958902 2.52393377]\n [2.86235725 1.44927499 2.88420866]\n [1.41702297 2.20668449 2.3486472 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.22it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5152.71it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5419.00it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,284 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.36235231 1.59613936 1.33800885]\n [0.38493044 1.51495096 1.21185401]\n [0.79004086 1.50473873 1.79091627]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.36235231 1.59613936 1.33800885]\n [0.38493044 1.51495096 1.21185401]\n [0.79004086 1.50473873 1.79091627]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.67it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,339 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.80590313 1.30512091 5.67075537]\n [4.27478475 1.07990391 4.9282529 ]\n [2.27867222 0.79992649 2.74808054]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.80590313 1.30512091 5.67075537]\n [4.27478475 1.07990391 4.9282529 ]\n [2.27867222 0.79992649 2.74808054]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:08,400 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.16829229  1.92680888  5.66831085]\n [ 1.14361383  1.93980949  5.00947833]\n [ 2.29315705  0.7441845  13.96806342]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.16829229  1.92680888  5.66831085]\n [ 1.14361383  1.93980949  5.00947833]\n [ 2.29315705  0.7441845  13.96806342]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 17.39it/s]    100%|##########| 3/3 [00:00<00:00, 25.96it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,454 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 6.28694358  0.94410541 22.13765247]\n [ 6.37214857  0.9337805  20.90432469]\n [ 4.54421961  0.5960027  12.97939054]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 6.28694358  0.94410541 22.13765247]\n [ 6.37214857  0.9337805  20.90432469]\n [ 4.54421961  0.5960027  12.97939054]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.75it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,509 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[12.2751103   0.53814923  3.62538593]\n [10.05510791  0.56011234  2.3855218 ]\n [ 2.08510155  3.97779948  2.76643303]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[12.2751103   0.53814923  3.62538593]\n [10.05510791  0.56011234  2.3855218 ]\n [ 2.08510155  3.97779948  2.76643303]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:08,561 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.79728296 1.32753672 0.7354865 ]\n [0.87324132 1.32366017 1.08197999]\n [0.76487814 2.01727935 2.86163404]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.79728296 1.32753672 0.7354865 ]\n [0.87324132 1.32366017 1.08197999]\n [0.76487814 2.01727935 2.86163404]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 28.17it/s]    100%|##########| 3/3 [00:00<00:00, 28.12it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,616 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.88513732 0.50906746 2.32405523]\n [4.43764651 0.41859196 2.03374464]\n [1.49725489 0.88049738 1.30962348]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.88513732 0.50906746 2.32405523]\n [4.43764651 0.41859196 2.03374464]\n [1.49725489 0.88049738 1.30962348]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:08,670 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.2057228  3.97806436 0.39663366]\n [0.21483115 3.4640344  0.34511111]\n [1.02724865 0.80328468 0.60817052]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.2057228  3.97806436 0.39663366]\n [0.21483115 3.4640344  0.34511111]\n [1.02724865 0.80328468 0.60817052]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 27.78it/s]    100%|##########| 3/3 [00:00<00:00, 27.72it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4542.57it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,725 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.95803537 1.24924546 1.72208583]\n [1.71125292 1.4135715  1.5224738 ]\n [3.13448532 0.89995997 6.09699857]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.95803537 1.24924546 1.72208583]\n [1.71125292 1.4135715  1.5224738 ]\n [3.13448532 0.89995997 6.09699857]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 55.29it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,780 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.19392688 0.82059416 2.46937545]\n [1.29491858 0.91257541 2.36033328]\n [5.87703384 0.37743749 9.93879412]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.19392688 0.82059416 2.46937545]\n [1.29491858 0.91257541 2.36033328]\n [5.87703384 0.37743749 9.93879412]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.88it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,895 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.94461225  1.17689987 16.71939594]\n [ 1.01999975  1.6148504   7.98653891]\n [ 1.05935364  0.97684135  4.86790722]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.94461225  1.17689987 16.71939594]\n [ 1.01999975  1.6148504   7.98653891]\n [ 1.05935364  0.97684135  4.86790722]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 26.36it/s]    100%|##########| 3/3 [00:00<00:00, 26.31it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4828.44it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:08,950 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.78556619 0.7278314  3.01580907]\n [1.76714478 0.72706977 2.92304532]\n [2.26173689 0.30410548 9.84661329]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.78556619 0.7278314  3.01580907]\n [1.76714478 0.72706977 2.92304532]\n [2.26173689 0.30410548 9.84661329]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 55.36it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5468.45it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,006 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.23796186 5.31608057 0.83811294]\n [0.19392739 5.96255397 0.87108843]\n [0.60829267 3.44304172 1.8877618 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.23796186 5.31608057 0.83811294]\n [0.19392739 5.96255397 0.87108843]\n [0.60829267 3.44304172 1.8877618 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 55.24it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,059 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.33242229 0.35911222 2.42917983]\n [1.26338022 0.39207955 2.40016393]\n [0.70360457 0.77797906 5.73576208]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.33242229 0.35911222 2.42917983]\n [1.26338022 0.39207955 2.40016393]\n [0.70360457 0.77797906 5.73576208]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.50it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4629.47it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,122 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.37395962 0.60787522 1.47152559]\n [0.35603094 0.61578981 1.37740889]\n [0.67768185 0.68386931 1.02651279]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.37395962 0.60787522 1.47152559]\n [0.35603094 0.61578981 1.37740889]\n [0.67768185 0.68386931 1.02651279]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 48.77it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,177 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.52098586 1.40203659 0.36203123]\n [0.43120872 1.62591106 0.35626504]\n [1.16687716 1.34135125 1.09795461]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.52098586 1.40203659 0.36203123]\n [0.43120872 1.62591106 0.35626504]\n [1.16687716 1.34135125 1.09795461]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.80it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5199.55it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,233 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.48873243 8.2364189  1.76867168]\n [0.4806747  8.34908539 1.81447601]\n [2.72182891 1.76659214 8.89327833]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.48873243 8.2364189  1.76867168]\n [0.4806747  8.34908539 1.81447601]\n [2.72182891 1.76659214 8.89327833]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.43it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5393.45it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5409.68it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5552.92it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,289 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.11641089 0.20843233 1.38743368]\n [1.90026676 0.19629326 1.31827074]\n [0.78584127 1.38847867 1.74006081]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.11641089 0.20843233 1.38743368]\n [1.90026676 0.19629326 1.31827074]\n [0.78584127 1.38847867 1.74006081]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:09,350 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[3.18855928 0.21062263 1.18874626]\n [3.27105028 0.2169815  1.15097918]\n [0.72177461 1.16326386 1.4536602 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[3.18855928 0.21062263 1.18874626]\n [3.27105028 0.2169815  1.15097918]\n [0.72177461 1.16326386 1.4536602 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 26.49it/s]    100%|##########| 3/3 [00:00<00:00, 26.44it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,406 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.36212073 1.65364626 2.37760306]\n [1.36812729 1.73034154 2.27926724]\n [2.21146286 0.92668236 3.25713624]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.36212073 1.65364626 2.37760306]\n [1.36812729 1.73034154 2.27926724]\n [2.21146286 0.92668236 3.25713624]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.70it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5236.33it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,460 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.46309449  1.30131684 10.67051355]\n [ 0.56210858  2.23409871  3.13008946]\n [ 1.83662121  1.21675134  5.03460169]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.46309449  1.30131684 10.67051355]\n [ 0.56210858  2.23409871  3.13008946]\n [ 1.83662121  1.21675134  5.03460169]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.39it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,515 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 0.31568172 10.80624137  1.14423111]\n [ 0.32865589 10.23022704  1.12717158]\n [ 1.08039867  1.34898366  1.76721969]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 0.31568172 10.80624137  1.14423111]\n [ 0.32865589 10.23022704  1.12717158]\n [ 1.08039867  1.34898366  1.76721969]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 55.04it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,571 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.84054783 0.30633399 3.87475845]\n [0.85935042 0.29487836 3.84325754]\n [0.99961394 0.63515683 2.87725633]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.84054783 0.30633399 3.87475845]\n [0.85935042 0.29487836 3.84325754]\n [0.99961394 0.63515683 2.87725633]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 52.84it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,627 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.29245805  0.54135509  2.74721462]\n [ 2.95023272  0.55470856  2.56992965]\n [ 5.10263025  1.14226489 15.74774532]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.29245805  0.54135509  2.74721462]\n [ 2.95023272  0.55470856  2.56992965]\n [ 5.10263025  1.14226489 15.74774532]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:09,679 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.18859507 1.0015073  0.32654795]\n [0.19920945 0.9650667  0.32414723]\n [0.6860501  1.00986391 1.78691828]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.18859507 1.0015073  0.32654795]\n [0.19920945 0.9650667  0.32414723]\n [0.6860501  1.00986391 1.78691828]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 28.24it/s]    100%|##########| 3/3 [00:00<00:00, 28.19it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,731 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.45225859  7.48733763  4.24620392]\n [ 1.1551511   6.22943273  3.319011  ]\n [ 6.33903924  1.93557967 23.73059774]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.45225859  7.48733763  4.24620392]\n [ 1.1551511   6.22943273  3.319011  ]\n [ 6.33903924  1.93557967 23.73059774]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.20it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5005.14it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,787 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.54869533 0.58627939 2.17857437]\n [1.55076267 0.57715794 2.10840417]\n [0.7676787  1.20161307 1.27697141]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.54869533 0.58627939 2.17857437]\n [1.55076267 0.57715794 2.10840417]\n [0.7676787  1.20161307 1.27697141]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.97it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4934.48it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5395.76it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5701.36it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5844.36it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5562.74it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5650.16it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5790.57it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5913.02it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5844.36it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5511.57it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5727.32it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5907.47it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5949.37it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5678.21it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5379.61it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5932.54it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5494.72it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,858 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.11357208 1.10226102 0.66434213]\n [0.85854348 0.98776117 0.51455866]\n [0.76839518 2.01468228 1.03754339]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.11357208 1.10226102 0.66434213]\n [0.85854348 0.98776117 0.51455866]\n [0.76839518 2.01468228 1.03754339]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:09,910 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.36185548 1.26556019 1.03458142]\n [1.31955296 0.66662329 0.60433115]\n [2.80675221 0.99219906 2.35782963]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.36185548 1.26556019 1.03458142]\n [1.31955296 0.66662329 0.60433115]\n [2.80675221 0.99219906 2.35782963]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 18.74it/s]    100%|##########| 3/3 [00:00<00:00, 27.98it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5212.47it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:09,964 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.95740553 0.71182272 4.15676132]\n [2.4379235  0.88866427 3.59885775]\n [3.37040348 0.42328836 5.62946039]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.95740553 0.71182272 4.15676132]\n [2.4379235  0.88866427 3.59885775]\n [3.37040348 0.42328836 5.62946039]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:10,016 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.90875868 4.29559478 1.71627543]\n [0.85332924 4.76930789 1.75053681]\n [1.26885019 0.63770376 3.96402886]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.90875868 4.29559478 1.71627543]\n [0.85332924 4.76930789 1.75053681]\n [1.26885019 0.63770376 3.96402886]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 19.19it/s]    100%|##########| 3/3 [00:00<00:00, 28.65it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,070 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.57433453 0.48260497 4.17219459]\n [1.29594973 0.5961753  3.92372258]\n [0.88622095 1.50463624 2.46713969]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.57433453 0.48260497 4.17219459]\n [1.29594973 0.5961753  3.92372258]\n [0.88622095 1.50463624 2.46713969]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.39it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 3586.92it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,134 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.47296164 2.0463655  0.24223318]\n [0.51168974 1.77390845 0.27142247]\n [0.97752534 0.90763298 1.89358284]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.47296164 2.0463655  0.24223318]\n [0.51168974 1.77390845 0.27142247]\n [0.97752534 0.90763298 1.89358284]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 47.57it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,189 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.18748163 1.53724199 0.78765384]\n [0.15603482 1.90668416 0.80180628]\n [0.87737396 0.77889677 3.71347822]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.18748163 1.53724199 0.78765384]\n [0.15603482 1.90668416 0.80180628]\n [0.87737396 0.77889677 3.71347822]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 55.42it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,249 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.60972415 1.24408833 7.66389699]\n [1.61386821 1.20635259 7.62797455]\n [1.52257542 0.24273127 3.31089598]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.60972415 1.24408833 7.66389699]\n [1.61386821 1.20635259 7.62797455]\n [1.52257542 0.24273127 3.31089598]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 50.54it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4482.69it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,303 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.32716423  3.02234667  7.53612074]\n [ 1.25686844  1.04627309  8.08431546]\n [ 9.03640694  2.57879093 80.30018218]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 1.32716423  3.02234667  7.53612074]\n [ 1.25686844  1.04627309  8.08431546]\n [ 9.03640694  2.57879093 80.30018218]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.20it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,356 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.69757468 0.24227549 2.2895882 ]\n [1.77644475 0.22213454 2.58094397]\n [1.03566943 1.7749146  5.7885165 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.69757468 0.24227549 2.2895882 ]\n [1.77644475 0.22213454 2.58094397]\n [1.03566943 1.7749146  5.7885165 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.89it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5363.56it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5535.82it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5806.60it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5929.74it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5833.52it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5980.47it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,415 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.99917817 1.50269942 2.84528128]\n [2.77636679 1.32352745 2.4987733 ]\n [0.24832712 1.28063747 3.2665846 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.99917817 1.50269942 2.84528128]\n [2.77636679 1.32352745 2.4987733 ]\n [0.24832712 1.28063747 3.2665846 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.56it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5073.75it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,469 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[3.71751905 0.49828483 0.81370686]\n [3.71889837 0.51020985 0.82930219]\n [1.99001747 1.15577478 1.2620033 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[3.71751905 0.49828483 0.81370686]\n [3.71889837 0.51020985 0.82930219]\n [1.99001747 1.15577478 1.2620033 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.22it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 4667.25it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,585 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.39344798 1.02472917 0.00795878]\n [0.42526267 0.8879805  0.02212526]\n [1.11861932 0.84251437 0.39347019]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.39344798 1.02472917 0.00795878]\n [0.42526267 0.8879805  0.02212526]\n [1.11861932 0.84251437 0.39347019]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 26.26it/s]    100%|##########| 3/3 [00:00<00:00, 26.21it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,639 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.05189894e-02 1.36849418e+00 1.05732194e-02]\n [3.47595021e-04 1.20963702e+01 6.34423783e-03]\n [9.68012781e-02 9.09132039e-02 2.79146358e-01]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.05189894e-02 1.36849418e+00 1.05732194e-02]\n [3.47595021e-04 1.20963702e+01 6.34423783e-03]\n [9.68012781e-02 9.09132039e-02 2.79146358e-01]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 56.13it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,694 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.17304126 0.79017714 1.64705197]\n [1.3357521  2.08203995 1.96385249]\n [2.06088405 0.70962557 4.61254886]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[2.17304126 0.79017714 1.64705197]\n [1.3357521  2.08203995 1.96385249]\n [2.06088405 0.70962557 4.61254886]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.39it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5402.71it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,750 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.48380039 0.31962806 3.38274125]\n [1.28010428 0.29281987 3.69253515]\n [0.64948266 0.87901023 1.53770399]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.48380039 0.31962806 3.38274125]\n [1.28010428 0.29281987 3.69253515]\n [0.64948266 0.87901023 1.53770399]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:10,802 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.92246953 1.38145656 0.58510137]\n [0.93579167 1.37404879 0.59817494]\n [1.05727091 0.52047877 1.08342308]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.92246953 1.38145656 0.58510137]\n [0.93579167 1.37404879 0.59817494]\n [1.05727091 0.52047877 1.08342308]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 18.86it/s]2022-10-26 22:54:10,866 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.47040127  0.43179417 14.93041317]\n [ 1.85286554  0.67150081 11.39321052]\n [ 6.87707921  1.54725362 32.67054444]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.47040127  0.43179417 14.93041317]\n [ 1.85286554  0.67150081 11.39321052]\n [ 6.87707921  1.54725362 32.67054444]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 17.65it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:10,921 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.92118564 0.88704794 0.46148629]\n [0.95450518 0.81263941 0.48508938]\n [1.01012934 1.39829842 2.13882043]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.92118564 0.88704794 0.46148629]\n [0.95450518 0.81263941 0.48508938]\n [1.01012934 1.39829842 2.13882043]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:10,975 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.14369832 0.99760622 1.5909814 ]\n [1.09821119 0.95327011 1.13794495]\n [1.15187795 1.5382586  0.55940431]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.14369832 0.99760622 1.5909814 ]\n [1.09821119 0.95327011 1.13794495]\n [1.15187795 1.5382586  0.55940431]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 18.47it/s]2022-10-26 22:54:11,029 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.99991118  1.86518861  3.34918537]\n [ 3.30231757  1.85247806  2.88777152]\n [13.38744136  1.51382259  7.95016854]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.99991118  1.86518861  3.34918537]\n [ 3.30231757  1.85247806  2.88777152]\n [13.38744136  1.51382259  7.95016854]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 18.48it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:11,084 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.05207496 1.25911174 0.85959389]\n [1.15166578 1.01173492 0.89510472]\n [0.61297262 1.06425736 1.1322929 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.05207496 1.25911174 0.85959389]\n [1.15166578 1.01173492 0.89510472]\n [0.61297262 1.06425736 1.1322929 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 54.98it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:11,211 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.08167191 0.39851606 0.24556036]\n [0.06890337 1.95593322 0.67855414]\n [3.25676275 0.42702339 0.62344713]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.08167191 0.39851606 0.24556036]\n [0.06890337 1.95593322 0.67855414]\n [3.25676275 0.42702339 0.62344713]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 23.73it/s]    100%|##########| 3/3 [00:00<00:00, 23.69it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:11,266 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.98076621 0.06559887 0.55282823]\n [1.93057409 0.06287228 0.64807112]\n [0.47493043 1.47153468 0.4945255 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[1.98076621 0.06559887 0.55282823]\n [1.93057409 0.06287228 0.64807112]\n [0.47493043 1.47153468 0.4945255 ]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    2022-10-26 22:54:11,320 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.18209725  1.61047896 25.88385257]\n [ 0.77926402  4.32690384 14.5357224 ]\n [ 3.45930176 10.615431   23.83383082]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[ 2.18209725  1.61047896 25.88385257]\n [ 0.77926402  4.32690384 14.5357224 ]\n [ 3.45930176 10.615431   23.83383082]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
     67%|######6   | 2/3 [00:00<00:00, 18.47it/s]    100%|##########| 3/3 [00:00<00:00, 27.58it/s]
      0%|          | 0/3 [00:00<?, ?it/s]2022-10-26 22:54:11,373 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.94825384 1.70034386 1.00696113]\n [0.98538527 1.42626512 0.82415387]\n [1.55589142 0.76774    0.43155714]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[0.94825384 1.70034386 1.00696113]\n [0.98538527 1.42626512 0.82415387]\n [1.55589142 0.76774    0.43155714]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 3/3 [00:00<00:00, 57.30it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 43.87it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5655.24it/s]
      0%|          | 0/3 [00:00<?, ?it/s]    100%|##########| 3/3 [00:00<00:00, 5888.12it/s]
      0%|          | 0/1 [00:00<?, ?it/s]2022-10-26 22:54:11,499 - ERROR - ['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.50122114 1.84696301 2.79471935]\n [4.91666868 1.81029176 3.12567603]\n [2.7526834  1.0352396  3.36614814]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    ERROR:pyglimer.request.preprocess:['IU.HRV.mseed', TypeError("write_info() missing 1 required positional argument: 'preproloc'")]
    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 392, in __waveform_loop
        st, crit, infodict = __rotate_qc(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 666, in __rotate_qc
        raise SNRError('QC rejected %s' % np.array2string(noisemat))
    pyglimer.waveform.preprocess.SNRError: 'QC rejected [[4.50122114 1.84696301 2.79471935]\n [4.91666868 1.81029176 3.12567603]\n [2.7526834  1.0352396  3.36614814]]'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 290, in __event_loop
        info = __waveform_loop(
      File "/home/runner/work/PyGLImER/PyGLImER/src/pyglimer/waveform/preprocess.py", line 421, in __waveform_loop
        write_info(network, station, infodict)
    TypeError: write_info() missing 1 required positional argument: 'preproloc'
    100%|##########| 1/1 [00:00<00:00, 18.44it/s]




.. GENERATED FROM PYTHON SOURCE LINES 175-192

First Receiver functions
------------------------

The following few section show how to plot 

1. Single raw RFs
2. A set of raw RFs
3. A move-out corrected RF
4. A set of move-out corrected RFs


Read the IU-HRV receiver functions as a Receiver function stream
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Let's read a receiver function set and see what it's all about! 
(i.e. let's look at what data a Receiver function trace contains
and how we can use it!)

.. GENERATED FROM PYTHON SOURCE LINES 192-200

.. code-block:: default


    from pyglimer.rf.create import read_rf

    path_to_rf = os.path.join(proj_dir, 'waveforms','RF','P','IU','HRV','*.sac')
    rfstream = read_rf(path_to_rf)

    print(f"Number of RFs: {len(rfstream)}")





.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    Number of RFs: 7




.. GENERATED FROM PYTHON SOURCE LINES 201-202

PyGLImER is based on Obspy, but to handle RFs we need some more attributes: 

.. GENERATED FROM PYTHON SOURCE LINES 202-209

.. code-block:: default


    from pprint import pprint

    rftrace = rfstream[0]
    pprint(rftrace.stats)






.. rst-class:: sphx-glr-script-out

 .. code-block:: none

    Stats({'sampling_rate': 10.0, 'delta': 0.1, 'starttime': UTCDateTime(2021, 1, 10, 4, 4, 10, 294538), 'endtime': UTCDateTime(2021, 1, 10, 4, 6, 40, 194538), 'npts': 1500, 'calib': 1.0, 'network': 'IU', 'station': 'HRV', 'location': '60', 'channel': 'PRF', 'sac': AttribDict({'delta': 0.1, 'depmin': -0.5170056, 'depmax': 0.6425919, 'scale': 1.0, 'b': 0.000538, 'e': 149.90054, 'o': -595.811, 'a': 30.00007, 'stla': 42.5064, 'stlo': -71.5583, 'stel': 200.0, 'evla': -24.0412, 'evlo': -66.5729, 'evdp': 217000.0, 'mag': 6.1, 'user1': 6.337349, 'baz': 175.01988, 'gcarc': 66.419815, 'depmen': 6.35307e-09, 'nzyear': 2021, 'nzjday': 10, 'nzhour': 4, 'nzmin': 4, 'nzsec': 10, 'nzmsec': 294, 'nvhdr': 6, 'npts': 1500, 'iftype': 1, 'iztype': 9, 'leven': 1, 'lpspol': 1, 'lovrok': 1, 'lcalda': 0, 'kstnm': 'HRV', 'khole': '60', 'kuser0': 'time', 'kuser1': 'P', 'kcmpnm': 'PRF', 'knetwk': 'IU'}), '_format': 'SAC', 'station_latitude': 42.5064, 'station_longitude': -71.5583, 'station_elevation': 200.0, 'event_latitude': -24.0412, 'event_longitude': -66.5729, 'event_depth': 217000.0, 'event_magnitude': 6.1, 'event_time': UTCDateTime(2021, 1, 10, 3, 54, 14, 483026), 'onset': UTCDateTime(2021, 1, 10, 4, 4, 40, 294071), 'type': 'time', 'phase': 'P', 'distance': 66.419815, 'back_azimuth': 175.01988, 'slowness': 6.337349})




.. GENERATED FROM PYTHON SOURCE LINES 210-226

First Receiver function plots
-----------------------------

If the Receiver functions haven't been further processed,
they are plotted as a function of time. A single receiver
function in the stream will be plotted as function of time
only. A full stream can make use of the distance measure saved
in the sac-header and plot an entire section as a function of
time and epicentral distance.

Plot single RF
++++++++++++++

Below we show how to plot the receiver function
as a function of time, and the clean option, which plots
the receiver function without any axes or text.

.. GENERATED FROM PYTHON SOURCE LINES 226-232

.. code-block:: default


    from pyglimer.plot.plot_utils import set_mpl_params

    # Plot RF
    rftrace.plot()




.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_002.png
   :alt: DataCollectionSAC
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_002.png
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none


    <AxesSubplot: xlabel='Conversion Time [s]', ylabel='A    '>



.. GENERATED FROM PYTHON SOURCE LINES 233-234

Let's zoom into the first 20 seconds (~200km)

.. GENERATED FROM PYTHON SOURCE LINES 234-237

.. code-block:: default


    rftrace.plot(lim=[0,20])




.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_003.png
   :alt: DataCollectionSAC
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_003.png
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none


    <AxesSubplot: xlabel='Conversion Time [s]', ylabel='A    '>



.. GENERATED FROM PYTHON SOURCE LINES 238-243

Plot RF section
+++++++++++++++

Since we have an entire stream of receiver functions at hand,
we can plot a section

.. GENERATED FROM PYTHON SOURCE LINES 243-246

.. code-block:: default


    rfstream.plot(scalingfactor=1)




.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_004.png
   :alt: PRF component
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_004.png
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none


    <AxesSubplot: title={'center': 'PRF component'}, xlabel='$\\Delta$ [$^{\\circ}$]', ylabel='Time [s]'>



.. GENERATED FROM PYTHON SOURCE LINES 247-249

Similar to the single RF plot we can provide time and 
epicentral distance limits:

.. GENERATED FROM PYTHON SOURCE LINES 249-256

.. code-block:: default


    timelimits = (0, 20)  # seconds  
    epilimits = (32, 36)  # epicentral distance
    rfstream.plot(
        scalingfactor=0.25, lim=timelimits, epilimits=epilimits,
        linewidth=0.75)




.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_005.png
   :alt: PRF component
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_005.png
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none


    <AxesSubplot: title={'center': 'PRF component'}, xlabel='$\\Delta$ [$^{\\circ}$]', ylabel='Time [s]'>



.. GENERATED FROM PYTHON SOURCE LINES 257-259

By increasing the scaling factor and removing the plotted lines, we can
already see trends:

.. GENERATED FROM PYTHON SOURCE LINES 259-265

.. code-block:: default


    rfstream.plot(
        scalingfactor=0.5, lim=timelimits, epilimits=epilimits, 
        line=False)





.. image-sg:: /tutorials/images/sphx_glr_DataCollectionSAC_006.png
   :alt: PRF component
   :srcset: /tutorials/images/sphx_glr_DataCollectionSAC_006.png
   :class: sphx-glr-single-img


.. rst-class:: sphx-glr-script-out

 .. code-block:: none


    <AxesSubplot: title={'center': 'PRF component'}, xlabel='$\\Delta$ [$^{\\circ}$]', ylabel='Time [s]'>



.. GENERATED FROM PYTHON SOURCE LINES 266-267

As simple as that you can create your own receiver functions with 
just a single smalle script.


.. rst-class:: sphx-glr-timing

   **Total running time of the script:** ( 1 minutes  32.928 seconds)


.. _sphx_glr_download_tutorials_DataCollectionSAC.py:

.. only:: html

  .. container:: sphx-glr-footer sphx-glr-footer-example


    .. container:: sphx-glr-download sphx-glr-download-python

      :download:`Download Python source code: DataCollectionSAC.py <DataCollectionSAC.py>`

    .. container:: sphx-glr-download sphx-glr-download-jupyter

      :download:`Download Jupyter notebook: DataCollectionSAC.ipynb <DataCollectionSAC.ipynb>`


.. only:: html

 .. rst-class:: sphx-glr-signature

    `Gallery generated by Sphinx-Gallery <https://sphinx-gallery.github.io>`_
